In [1]:
import numpy as np
import pandas as pd
import tensorflow 
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
data=pd.read_csv('pima_indians-diabetes.csv')
data.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [3]:
data.shape

(767, 9)

In [4]:
X=data.iloc[:,0:8].values
y=data.iloc[:,8].values

In [5]:
X


array([[1.00e+00, 8.50e+01, 6.60e+01, ..., 2.66e+01, 3.51e-01, 3.10e+01],
       [8.00e+00, 1.83e+02, 6.40e+01, ..., 2.33e+01, 6.72e-01, 3.20e+01],
       [1.00e+00, 8.90e+01, 6.60e+01, ..., 2.81e+01, 1.67e-01, 2.10e+01],
       ...,
       [5.00e+00, 1.21e+02, 7.20e+01, ..., 2.62e+01, 2.45e-01, 3.00e+01],
       [1.00e+00, 1.26e+02, 6.00e+01, ..., 3.01e+01, 3.49e-01, 4.70e+01],
       [1.00e+00, 9.30e+01, 7.00e+01, ..., 3.04e+01, 3.15e-01, 2.30e+01]])

In [6]:
y

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,

In [7]:
model=Sequential()
model.add(Dense(64,input_dim=8,activation='sigmoid'))
model.add(Dense(32,activation='relu'))
model.add(Dense(8,activation='tanh'))

model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [8]:
import warnings

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

model.fit(X_train,y_train,epochs=1000,verbose=2)


Train on 613 samples
Epoch 1/1000
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
613/613 - 3s - loss: 0.7336 - accuracy: 0.5351
Epoch 2/1000
613/613 - 0s - loss: 0.6447 - accuracy: 0.6395
Epoch 3/1000
613/613 - 0s - loss: 0.6300 - accuracy: 0.6460
Epoch 4/1000
613/613 - 0s - loss: 0.6217 - accuracy: 0.6542
Epoch 5/1000
613/613 - 0s - loss: 0.6152 - accuracy: 0.6476
Epoch 6/1000
613/613 - 0s - loss: 0.6029 - accuracy: 0.6607
Epoch 7/1000
613/613 - 0s - loss: 0.6023 - accuracy: 0.6542
Epoch 8/1000
613/613 - 0s - loss: 0.5946 - accuracy: 0.6672
Epoch 9/1000
613/613 - 0s - loss: 0.5930 - accuracy: 0.6639
Epoch 10/1000
613/613 - 0s - loss: 0.5846 - accuracy: 0.7096
Epoch 11/1000
613/613 - 0s - loss: 0.5843 - accuracy: 0.6900
Epoch 12/1000
613/613 - 0s - loss: 0.5795 - accuracy: 0.6803
Epoch 13/1000
613/613 - 0s - loss: 0.5730 - accuracy: 0.6949
Epoch 14/1000
613/613 - 0s - loss: 0.5770 - accuracy: 0.6835
Epoch 15/1000
613/613 - 0s - loss: 0.568

Epoch 117/1000
613/613 - 0s - loss: 0.3683 - accuracy: 0.8336
Epoch 118/1000
613/613 - 0s - loss: 0.3774 - accuracy: 0.8336
Epoch 119/1000
613/613 - 0s - loss: 0.3699 - accuracy: 0.8303
Epoch 120/1000
613/613 - 0s - loss: 0.3692 - accuracy: 0.8254
Epoch 121/1000
613/613 - 0s - loss: 0.3614 - accuracy: 0.8401
Epoch 122/1000
613/613 - 0s - loss: 0.3605 - accuracy: 0.8369
Epoch 123/1000
613/613 - 0s - loss: 0.3683 - accuracy: 0.8222
Epoch 124/1000
613/613 - 0s - loss: 0.3747 - accuracy: 0.8140
Epoch 125/1000
613/613 - 0s - loss: 0.3588 - accuracy: 0.8385
Epoch 126/1000
613/613 - 0s - loss: 0.3745 - accuracy: 0.8222
Epoch 127/1000
613/613 - 0s - loss: 0.3635 - accuracy: 0.8287
Epoch 128/1000
613/613 - 0s - loss: 0.3704 - accuracy: 0.8140
Epoch 129/1000
613/613 - 0s - loss: 0.3752 - accuracy: 0.8189
Epoch 130/1000
613/613 - 0s - loss: 0.3728 - accuracy: 0.8157
Epoch 131/1000
613/613 - 0s - loss: 0.3624 - accuracy: 0.8352
Epoch 132/1000
613/613 - 0s - loss: 0.3533 - accuracy: 0.8401
Epoch 13

Epoch 249/1000
613/613 - 0s - loss: 0.3141 - accuracy: 0.8679
Epoch 250/1000
613/613 - 0s - loss: 0.2978 - accuracy: 0.8711
Epoch 251/1000
613/613 - 0s - loss: 0.2822 - accuracy: 0.8809
Epoch 252/1000
613/613 - 0s - loss: 0.2903 - accuracy: 0.8630
Epoch 253/1000
613/613 - 0s - loss: 0.2961 - accuracy: 0.8597
Epoch 254/1000
613/613 - 0s - loss: 0.3453 - accuracy: 0.8320
Epoch 255/1000
613/613 - 0s - loss: 0.3260 - accuracy: 0.8646
Epoch 256/1000
613/613 - 0s - loss: 0.3024 - accuracy: 0.8630
Epoch 257/1000
613/613 - 0s - loss: 0.2959 - accuracy: 0.8613
Epoch 258/1000
613/613 - 0s - loss: 0.3494 - accuracy: 0.8401
Epoch 259/1000
613/613 - 0s - loss: 0.2790 - accuracy: 0.8760
Epoch 260/1000
613/613 - 0s - loss: 0.2926 - accuracy: 0.8630
Epoch 261/1000
613/613 - 0s - loss: 0.2779 - accuracy: 0.8809
Epoch 262/1000
613/613 - 0s - loss: 0.2932 - accuracy: 0.8646
Epoch 263/1000
613/613 - 0s - loss: 0.2749 - accuracy: 0.8711
Epoch 264/1000
613/613 - 0s - loss: 0.2877 - accuracy: 0.8646
Epoch 26

613/613 - 0s - loss: 0.2649 - accuracy: 0.8744
Epoch 382/1000
613/613 - 0s - loss: 0.2508 - accuracy: 0.8825
Epoch 383/1000
613/613 - 0s - loss: 0.2791 - accuracy: 0.8842
Epoch 384/1000
613/613 - 0s - loss: 0.2633 - accuracy: 0.8809
Epoch 385/1000
613/613 - 0s - loss: 0.2517 - accuracy: 0.8907
Epoch 386/1000
613/613 - 0s - loss: 0.2510 - accuracy: 0.8874
Epoch 387/1000
613/613 - 0s - loss: 0.2880 - accuracy: 0.8760
Epoch 388/1000
613/613 - 0s - loss: 0.2585 - accuracy: 0.8760
Epoch 389/1000
613/613 - 0s - loss: 0.2463 - accuracy: 0.8940
Epoch 390/1000
613/613 - 0s - loss: 0.2802 - accuracy: 0.8744
Epoch 391/1000
613/613 - 0s - loss: 0.2410 - accuracy: 0.9005
Epoch 392/1000
613/613 - 0s - loss: 0.2402 - accuracy: 0.9005
Epoch 393/1000
613/613 - 0s - loss: 0.2261 - accuracy: 0.9005
Epoch 394/1000
613/613 - 0s - loss: 0.2497 - accuracy: 0.8923
Epoch 395/1000
613/613 - 0s - loss: 0.2318 - accuracy: 0.8923
Epoch 396/1000
613/613 - 0s - loss: 0.2382 - accuracy: 0.8858
Epoch 397/1000
613/613 

Epoch 514/1000
613/613 - 0s - loss: 0.2679 - accuracy: 0.8744
Epoch 515/1000
613/613 - 0s - loss: 0.2647 - accuracy: 0.8956
Epoch 516/1000
613/613 - 0s - loss: 0.2673 - accuracy: 0.8662
Epoch 517/1000
613/613 - 0s - loss: 0.2168 - accuracy: 0.9201
Epoch 518/1000
613/613 - 0s - loss: 0.2218 - accuracy: 0.9005
Epoch 519/1000
613/613 - 0s - loss: 0.2084 - accuracy: 0.9135
Epoch 520/1000
613/613 - 0s - loss: 0.2118 - accuracy: 0.9086
Epoch 521/1000
613/613 - 0s - loss: 0.2280 - accuracy: 0.9005
Epoch 522/1000
613/613 - 0s - loss: 0.2311 - accuracy: 0.9086
Epoch 523/1000
613/613 - 0s - loss: 0.2185 - accuracy: 0.9103
Epoch 524/1000
613/613 - 0s - loss: 0.2506 - accuracy: 0.8825
Epoch 525/1000
613/613 - 0s - loss: 0.2312 - accuracy: 0.8891
Epoch 526/1000
613/613 - 0s - loss: 0.2516 - accuracy: 0.8793
Epoch 527/1000
613/613 - 0s - loss: 0.2219 - accuracy: 0.9038
Epoch 528/1000
613/613 - 0s - loss: 0.2182 - accuracy: 0.9086
Epoch 529/1000
613/613 - 0s - loss: 0.2486 - accuracy: 0.8940
Epoch 53

Epoch 647/1000
613/613 - 0s - loss: 0.1850 - accuracy: 0.9217
Epoch 648/1000
613/613 - 0s - loss: 0.1742 - accuracy: 0.9331
Epoch 649/1000
613/613 - 0s - loss: 0.1685 - accuracy: 0.9299
Epoch 650/1000
613/613 - 0s - loss: 0.2283 - accuracy: 0.9152
Epoch 651/1000
613/613 - 0s - loss: 0.2234 - accuracy: 0.9005
Epoch 652/1000
613/613 - 0s - loss: 0.1964 - accuracy: 0.9184
Epoch 653/1000
613/613 - 0s - loss: 0.1926 - accuracy: 0.9201
Epoch 654/1000
613/613 - 0s - loss: 0.2097 - accuracy: 0.9152
Epoch 655/1000
613/613 - 0s - loss: 0.1933 - accuracy: 0.9201
Epoch 656/1000
613/613 - 0s - loss: 0.1937 - accuracy: 0.9184
Epoch 657/1000
613/613 - 0s - loss: 0.1841 - accuracy: 0.9168
Epoch 658/1000
613/613 - 0s - loss: 0.1862 - accuracy: 0.9266
Epoch 659/1000
613/613 - 0s - loss: 0.1761 - accuracy: 0.9347
Epoch 660/1000
613/613 - 0s - loss: 0.1660 - accuracy: 0.9380
Epoch 661/1000
613/613 - 0s - loss: 0.1691 - accuracy: 0.9250
Epoch 662/1000
613/613 - 0s - loss: 0.1816 - accuracy: 0.9282
Epoch 66

Epoch 780/1000
613/613 - 0s - loss: 0.2488 - accuracy: 0.8907
Epoch 781/1000
613/613 - 0s - loss: 0.1873 - accuracy: 0.9315
Epoch 782/1000
613/613 - 0s - loss: 0.2026 - accuracy: 0.9201
Epoch 783/1000
613/613 - 0s - loss: 0.2264 - accuracy: 0.9070
Epoch 784/1000
613/613 - 0s - loss: 0.2205 - accuracy: 0.9070
Epoch 785/1000
613/613 - 0s - loss: 0.1905 - accuracy: 0.9201
Epoch 786/1000
613/613 - 0s - loss: 0.1541 - accuracy: 0.9478
Epoch 787/1000
613/613 - 0s - loss: 0.1394 - accuracy: 0.9560
Epoch 788/1000
613/613 - 0s - loss: 0.1449 - accuracy: 0.9462
Epoch 789/1000
613/613 - 0s - loss: 0.1426 - accuracy: 0.9527
Epoch 790/1000
613/613 - 0s - loss: 0.1576 - accuracy: 0.9347
Epoch 791/1000
613/613 - 0s - loss: 0.1548 - accuracy: 0.9299
Epoch 792/1000
613/613 - 0s - loss: 0.1611 - accuracy: 0.9396
Epoch 793/1000
613/613 - 0s - loss: 0.1624 - accuracy: 0.9413
Epoch 794/1000
613/613 - 0s - loss: 0.1604 - accuracy: 0.9445
Epoch 795/1000
613/613 - 0s - loss: 0.1710 - accuracy: 0.9168
Epoch 79

Epoch 913/1000
613/613 - 0s - loss: 0.1183 - accuracy: 0.9560
Epoch 914/1000
613/613 - 0s - loss: 0.1403 - accuracy: 0.9429
Epoch 915/1000
613/613 - 0s - loss: 0.1727 - accuracy: 0.9315
Epoch 916/1000
613/613 - 0s - loss: 0.1621 - accuracy: 0.9233
Epoch 917/1000
613/613 - 0s - loss: 0.1525 - accuracy: 0.9364
Epoch 918/1000
613/613 - 0s - loss: 0.1501 - accuracy: 0.9413
Epoch 919/1000
613/613 - 0s - loss: 0.1490 - accuracy: 0.9347
Epoch 920/1000
613/613 - 0s - loss: 0.1746 - accuracy: 0.9396
Epoch 921/1000
613/613 - 0s - loss: 0.2587 - accuracy: 0.8923
Epoch 922/1000
613/613 - 0s - loss: 0.2995 - accuracy: 0.8711
Epoch 923/1000
613/613 - 0s - loss: 0.1908 - accuracy: 0.9217
Epoch 924/1000
613/613 - 0s - loss: 0.1640 - accuracy: 0.9331
Epoch 925/1000
613/613 - 0s - loss: 0.1714 - accuracy: 0.9331
Epoch 926/1000
613/613 - 0s - loss: 0.2760 - accuracy: 0.8760
Epoch 927/1000
613/613 - 0s - loss: 0.2474 - accuracy: 0.8842
Epoch 928/1000
613/613 - 0s - loss: 0.1620 - accuracy: 0.9299
Epoch 92

In [15]:
y_pred = model.predict(X_test)
#Converting predictions to label
pred = list()
for i in range(len(y_pred)):
    pred.append(np.argmax(y_pred[i]))
#Converting one hot encoded test label to label
test = list()
for i in range(len(y_test)):
    test.append(np.argmax(y_test[i]))

In [10]:
scores=model.evaluate(X_test,y_test)
print(model.summary())
print(scores)

154/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [17]:
model.predict_classes(X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [12]:
a=data.iloc[0:3,:-1]
a

6  148  72  35   0  33.6  0.627  50
0  1   85  66  29   0  26.6  0.351  31
1  8  183  64   0   0  23.3  0.672  32
2  1   89  66  23  94  28.1  0.167  21

In [13]:
model.predict_classes(a)

array([[0],
       [1],
       [0]])

In [14]:
model.fit(X,y,validation_split=0.2,epochs=100,verbose=2,batch_size=64)

Train on 613 samples, validate on 154 samples
Epoch 1/100
613/613 - 0s - loss: 0.3783 - accuracy: 0.8907 - val_loss: 0.4195 - val_accuracy: 0.8571
Epoch 2/100
613/613 - 0s - loss: 0.3346 - accuracy: 0.8923 - val_loss: 0.3805 - val_accuracy: 0.8896
Epoch 3/100
613/613 - 0s - loss: 0.3073 - accuracy: 0.8891 - val_loss: 0.3802 - val_accuracy: 0.9026
Epoch 4/100
613/613 - 0s - loss: 0.2859 - accuracy: 0.8923 - val_loss: 0.4040 - val_accuracy: 0.8766
Epoch 5/100
613/613 - 0s - loss: 0.2703 - accuracy: 0.9119 - val_loss: 0.3801 - val_accuracy: 0.8831
Epoch 6/100
613/613 - 0s - loss: 0.2585 - accuracy: 0.9086 - val_loss: 0.4160 - val_accuracy: 0.8701
Epoch 7/100
613/613 - 0s - loss: 0.2472 - accuracy: 0.9201 - val_loss: 0.4057 - val_accuracy: 0.8636
Epoch 8/100
613/613 - 0s - loss: 0.2474 - accuracy: 0.9086 - val_loss: 0.4286 - val_accuracy: 0.8831
Epoch 9/100
613/613 - 0s - loss: 0.2472 - accuracy: 0.9119 - val_loss: 0.4197 - val_accuracy: 0.8506
Epoch 10/100
613/613 - 0s - loss: 0.2268 - ac

Epoch 81/100
613/613 - 0s - loss: 0.1517 - accuracy: 0.9478 - val_loss: 0.5089 - val_accuracy: 0.8312
Epoch 82/100
613/613 - 0s - loss: 0.1574 - accuracy: 0.9478 - val_loss: 0.5049 - val_accuracy: 0.8377
Epoch 83/100
613/613 - 0s - loss: 0.1533 - accuracy: 0.9413 - val_loss: 0.5338 - val_accuracy: 0.8117
Epoch 84/100
613/613 - 0s - loss: 0.1534 - accuracy: 0.9396 - val_loss: 0.5701 - val_accuracy: 0.8117
Epoch 85/100
613/613 - 0s - loss: 0.1617 - accuracy: 0.9445 - val_loss: 0.5184 - val_accuracy: 0.8247
Epoch 86/100
613/613 - 0s - loss: 0.1649 - accuracy: 0.9396 - val_loss: 0.5156 - val_accuracy: 0.8312
Epoch 87/100
613/613 - 0s - loss: 0.1550 - accuracy: 0.9462 - val_loss: 0.5258 - val_accuracy: 0.8377
Epoch 88/100
613/613 - 0s - loss: 0.1526 - accuracy: 0.9478 - val_loss: 0.5273 - val_accuracy: 0.8312
Epoch 89/100
613/613 - 0s - loss: 0.1526 - accuracy: 0.9445 - val_loss: 0.5225 - val_accuracy: 0.8182
Epoch 90/100
613/613 - 0s - loss: 0.1444 - accuracy: 0.9462 - val_loss: 0.5299 - v

In [27]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 64)                576       
_________________________________________________________________
dense_8 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 264       
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 9         
Total params: 2,929
Trainable params: 2,929
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.predict_classes(a)

array([[0],
       [1],
       [0]])

In [30]:
b=data.iloc[205:208,:]
b

6  148   72  35    0  33.6  0.627  50  1
205  8  196   76  29  280  37.5  0.605  57  1
206  5  162  104   0    0  37.7  0.151  52  1
207  1   96   64  27   87  33.2  0.289  21  0

In [31]:
b=data.iloc[205:208,:-1]

In [32]:
model.predict_classes(b)

array([[1],
       [1],
       [0]])